-- ตารางรอบการนั่งโต๊ะ (เปิดตอนพนักงานสร้าง QR)
create table sessions (
  id bigint generated by default as identity primary key,
  table_number int not null,
  status text not null default 'open', -- open | closed
  created_at timestamptz not null default now()
);

-- หมวดหมู่เมนู
create table menu_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order int not null default 0
);

-- รายการเมนูย่อย (มีราคาต่อรายการ เพราะร้านกาแฟคิดราคาตามแก้ว ไม่ใช่บุฟเฟต์)
create table menu_items (
  id bigint generated by default as identity primary key,
  category_id bigint references menu_categories(id),
  name text not null,
  price numeric not null default 0
);

-- ออเดอร์ที่ลูกค้าส่งเข้าครัว/บาร์ (เก็บรายการเป็นชุดเดียวต่อ 1 ครั้งที่กดส่ง)
create table orders (
  id bigint generated by default as identity primary key,
  session_id bigint references sessions(id),
  table_number int not null,
  items jsonb not null,       -- เช่น [{"name":"ลาเต้เย็น","quantity":2,"price":55}]
  status text not null default 'received', -- received | cooking | served
  created_at timestamptz not null default now()
);

-- เปิดสิทธิ์การเข้าถึง (สำหรับการเรียนรู้ — ให้อ่าน/เขียนได้ทุกคน)
alter table sessions enable row level security;
alter table menu_categories enable row level security;
alter table menu_items enable row level security;
alter table orders enable row level security;

create policy "allow all - sessions" on sessions for all using (true) with check (true);
create policy "allow all - menu_categories" on menu_categories for all using (true) with check (true);
create policy "allow all - menu_items" on menu_items for all using (true) with check (true);
create policy "allow all - orders" on orders for all using (true) with check (true);

-- ใส่หมวดหมู่และเมนูตัวอย่างของร้านกาแฟ
insert into menu_categories (name, sort_order) values
('กาแฟร้อน', 1), ('กาแฟเย็น/ปั่น', 2), ('ชา/เครื่องดื่มอื่นๆ', 3), ('เบเกอรี่/ของทานเล่น', 4);

insert into menu_items (category_id, name, price)
select id, item, price from menu_categories,
  lateral (values
    ('เอสเพรสโซ่', 45),
    ('อเมริกาโน่ร้อน', 50),
    ('ลาเต้ร้อน', 55),
    ('คาปูชิโน่ร้อน', 55)
  ) as t(item, price)
where menu_categories.name = 'กาแฟร้อน'
union all
select id, item, price from menu_categories,
  lateral (values
    ('อเมริกาโน่เย็น', 55),
    ('ลาเต้เย็น', 60),
    ('คาปูชิโน่เย็น', 60),
    ('โคลด์บรูว์', 65),
    ('มอคค่าปั่น', 70)
  ) as t(item, price)
where menu_categories.name = 'กาแฟเย็น/ปั่น'
union all
select id, item, price from menu_categories,
  lateral (values
    ('ชาไทยเย็น', 50),
    ('ชาเขียวมัทฉะเย็น', 60),
    ('โกโก้เย็น', 60),
    ('น้ำส้มคั้น', 50)
  ) as t(item, price)
where menu_categories.name = 'ชา/เครื่องดื่มอื่นๆ'
union all
select id, item, price from menu_categories,
  lateral (values
    ('ครัวซองต์เนย', 45),
    ('บราวนี่', 55),
    ('ชีสเค้ก', 65),
    ('คุกกี้', 30)
  ) as t(item, price)
where menu_categories.name = 'เบเกอรี่/ของทานเล่น';
